variables:
  GIT_SUBMODULE_STRATEGY: normal
  KUBERNETES_VERSION: 1.17.17

stages:
  - build
  - release

build:
  stage: build
  tags: [shell]
  script:
    - ./build/run.sh make kubelet | grep -v parse.go
    - ./build/run.sh make kubectl | grep -v parse.go
    - tree _output
  cache:
    policy: push
    key: "$CI_COMMIT_SHA"
    paths:
      - _output/dockerized/bin/linux/amd64/kubectl
      - _output/dockerized/bin/linux/amd64/kubelet

release:
  stage: release
  tags: [shell]
  script:
    - echo "[INFO] Uploading https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${CI_COMMIT_SHA}/kubelet"
    - |
      cd _output/dockerized/bin/linux/amd64/
      for binary in *; do
        curl -f -v -X PUT -H "Content-Type: application/octet-stream" -H "x-ms-date: $(date -Ru | sed -e 's/\\+0000/GMT/' -e 's/UTC/GMT/')" -H "x-ms-version: 2018-03-28" -H "x-ms-blob-type: BlockBlob" --data-binary @${binary} "https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${CI_COMMIT_SHA}/${binary}${AZURE_RELEASES_STORAGE_TOKEN}"
        curl -f -v -X PUT -H "Content-Type: application/octet-stream" -H "x-ms-date: $(date -Ru | sed -e 's/\\+0000/GMT/' -e 's/UTC/GMT/')" -H "x-ms-version: 2018-03-28" -H "x-ms-blob-type: BlockBlob" --data-binary $(md5sum ${binary}) "https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${CI_COMMIT_SHA}/${binary}.md5${AZURE_RELEASES_STORAGE_TOKEN}"
        curl -f -v -X PUT -H "Content-Type: application/octet-stream" -H "x-ms-date: $(date -Ru | sed -e 's/\\+0000/GMT/' -e 's/UTC/GMT/')" -H "x-ms-version: 2018-03-28" -H "x-ms-blob-type: BlockBlob" --data-binary @${binary} "https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${KUBERNETES_VERSION}/${binary}${AZURE_RELEASES_STORAGE_TOKEN}"
        curl -f -v -X PUT -H "Content-Type: application/octet-stream" -H "x-ms-date: $(date -Ru | sed -e 's/\\+0000/GMT/' -e 's/UTC/GMT/')" -H "x-ms-version: 2018-03-28" -H "x-ms-blob-type: BlockBlob" --data-binary $(md5sum ${binary}) "https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${KUBERNETES_VERSION}/${binary}.md5${AZURE_RELEASES_STORAGE_TOKEN}"
      done
  cache:
    policy: pull
    key: "$CI_COMMIT_SHA"
    paths:
      - _output/dockerized/bin/linux/amd64/kubectl
      - _output/dockerized/bin/linux/amd64/kubelet
  only:
    - v1.17-vesdev
