variables:
  GIT_SUBMODULE_STRATEGY: normal
  KUBERNETES_VERSION: 1.22.16
  KUBE_GIT_VERSION_FILE: version

stages:
  - build
  - vuln-scan
  - release

build:
  stage: build
  tags: [shell]
  before_script:
    - docker system prune -f
  script:
  - echo "KUBE_GIT_COMMIT=${CI_COMMIT_SHA}" > version
  - echo "KUBE_GIT_TREE_STATE=clean" >> version
  - echo "KUBE_GIT_VERSION=v${KUBERNETES_VERSION}-ves" >> version
  - echo "KUBE_GIT_MAJOR=1" >> version
  - echo "KUBE_GIT_MINOR=22" >> version
  - cat version

  # build binaries
  - ./build/run.sh make clean
  - ./build/run.sh make kubelet | grep -v parse.go
  - ./build/run.sh make kubectl | grep -v parse.go
  - tree _output

  # check version of binaries
  - ./_output/dockerized/bin/linux/amd64/kubelet --version
  - ./_output/dockerized/bin/linux/amd64/kubectl version --client
  - ./_output/dockerized/bin/linux/amd64/kubelet --version | grep "${KUBERNETES_VERSION}"
  - ./_output/dockerized/bin/linux/amd64/kubectl version --client | grep "${KUBERNETES_VERSION}"

  cache:
    policy: push
    key: "$CI_COMMIT_SHA"
    paths:
      - _output/dockerized/bin/linux/amd64/kubectl
      - _output/dockerized/bin/linux/amd64/kubelet

release:
  stage: release
  tags: [shell]
  script:
    - echo "[INFO] Uploading https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${CI_COMMIT_SHA}/kubelet"
    - |
      cd _output/dockerized/bin/linux/amd64/
      for binary in *; do
        curl -f -v -X PUT -H "Content-Type: application/octet-stream" -H "x-ms-date: $(date -Ru | sed -e 's/\\+0000/GMT/' -e 's/UTC/GMT/')" -H "x-ms-version: 2018-03-28" -H "x-ms-blob-type: BlockBlob" --data-binary @${binary} "https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${CI_COMMIT_SHA}/${binary}${AZURE_RELEASES_STORAGE_TOKEN}"
        curl -f -v -X PUT -H "Content-Type: application/octet-stream" -H "x-ms-date: $(date -Ru | sed -e 's/\\+0000/GMT/' -e 's/UTC/GMT/')" -H "x-ms-version: 2018-03-28" -H "x-ms-blob-type: BlockBlob" --data-binary $(md5sum ${binary}) "https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${CI_COMMIT_SHA}/${binary}.md5${AZURE_RELEASES_STORAGE_TOKEN}"
        echo curl -f -v -X PUT -H "Content-Type: application/octet-stream" -H "x-ms-date: $(date -Ru | sed -e 's/\\+0000/GMT/' -e 's/UTC/GMT/')" -H "x-ms-version: 2018-03-28" -H "x-ms-blob-type: BlockBlob" --data-binary @${binary} "https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${KUBERNETES_VERSION}/${binary}${AZURE_RELEASES_STORAGE_TOKEN}"
        echo curl -f -v -X PUT -H "Content-Type: application/octet-stream" -H "x-ms-date: $(date -Ru | sed -e 's/\\+0000/GMT/' -e 's/UTC/GMT/')" -H "x-ms-version: 2018-03-28" -H "x-ms-blob-type: BlockBlob" --data-binary $(md5sum ${binary}) "https://${AZURE_RELEASES_STORAGE_ACCOUNT}.blob.core.windows.net/releases/kubernetes/${KUBERNETES_VERSION}/${binary}.md5${AZURE_RELEASES_STORAGE_TOKEN}"
      done
  cache:
    policy: pull
    key: "$CI_COMMIT_SHA"
    paths:
      - _output/dockerized/bin/linux/amd64/kubectl
      - _output/dockerized/bin/linux/amd64/kubelet
  only:
    - /^.+-vesdev$/
    - /^.+-ves$/

include:
- project: volterra/security/security-config/cicd-includes
  ref: main
  file: whitesource/wss-golang.yml
